### ISSUE TITLE
MySQL2 for Node Arbitrary Code Injection

### ISSUE THREAD

**Issue by AGiljanovic** [codeuniversity/code-idp#24]
Versions of the package mysql2 before 3.9.7 are vulnerable to Arbitrary Code Injection due to improper sanitization of the timezone parameter in the readCodeFor function by calling a native MySQL Server date/time function.

**Fix:** Update the package version

See [link](https://github.com/codeuniversity/code-idp/security/dependabot/17)

**Comment by NewerKey** [comment]
updated package to unaffected version as suggested.
